version: '3'
services:
  live3000-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=live3000db
    ports:
      - "5432:5432"